# Aqui trabajamos con https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import matplotlib as plt

import seaborn as sns

In [2]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_failure_clinical_records = fetch_ucirepo(id=519)

# data (as pandas dataframes)
X = heart_failure_clinical_records.data.features
y = heart_failure_clinical_records.data.targets

# metadata
print(heart_failure_clinical_records.metadata)

# variable information
print(heart_failure_clinical_records.variables)

{'uci_id': 519, 'name': 'Heart Failure Clinical Records', 'repository_url': 'https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records', 'data_url': 'https://archive.ics.uci.edu/static/public/519/data.csv', 'abstract': 'This dataset contains the medical records of 299 patients who had heart failure, collected during their follow-up period, where each patient profile has 13 clinical features.', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Regression', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 299, 'num_features': 12, 'feature_types': ['Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['death_event'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2020, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5Z89R', 'creators': [], 'intro_paper': {'ID': 286, 'type': 'NATIVE', 'title': 'Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone', 'authors': 'D. Chicco, Giuseppe Jurman', 'venue': 'BMC Medical Informatics and Decision Making', 'year': 2020, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/e64579d8593140396b518682bb3a47ba246684eb', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '32013925', 'pmcid': None}, 'additional_info': {'summary': 'A detailed description of the dataset can be found in the Dataset section of the following paper: \r\n\r\nDavide Chicco, Giuseppe Jurman: "Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone". BMC Medical Informatics and Decision Making 20, 16 (2020). https://doi.org/10.1186/s12911-020-1023-5 \r\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Thirteen (13) clinical features:\n\n- age: age of the patient (years)\n- anaemia: decrease of red blood cells or hemoglobin (boolean)\n- creatinine phosphokinase  (CPK): level of the CPK enzyme in the blood (mcg/L)\n- diabetes: if the patient has diabetes (boolean)\n- ejection fraction: percentage of blood leaving the heart at each contraction  (percentage)\n- high blood pressure: if the patient has hypertension (boolean)\n- platelets: platelets in the blood (kiloplatelets/mL)\n- sex: woman or man (binary)\n- serum creatinine: level of serum creatinine in the blood (mg/dL)\n- serum sodium: level of serum sodium in the blood (mEq/L)\n- smoking: if the patient smokes or not (boolean)\n- time: follow-up period (days)\n- [target] death event: if the patient died during the follow-up period (boolean)\n\nFor more information, please check Table 1, Table 2, and Table 3 of the following paper: \n\nDavide Chicco, Giuseppe Jurman: "Machine learning can predict survival of patients with heart failure from serum creatinine and ejection fraction alone". BMC Medical Informatics and Decision Making 20, 16 (2020). https://doi.org/10.1186/s12911-020-1023-5 \n', 'citation': None}}
                        name     role        type demographic  \
0                        age  Feature     Integer         Age
1                    anaemia  Feature      Binary        None
2   creatinine_phosphokinase  Feature     Integer        None
3                   diabetes  Feature      Binary        None
4          ejection_fraction  Feature     Integer        None
5        high_blood_pressure  Feature      Binary        None
6                  platelets  Feature  Continuous        None
7           serum_creatinine  Feature  Continuous        None
8               serum_sodium  Feature     Integer        None
9                        sex  Feature      Binary         Sex
10                   smoking  Feature      Binary        None
11                      time  Feature     Integer        None
12               death_event   Target      Binary        None

                                          description             units  \
0                                  age of the patient             years
1           decrease of red blood cells or hemoglobin              None
2                level of the CPK enzyme in the blood             mcg/L
3                         if the patient has diabetes              None
4   percentage of blood leaving the heart at each ...                 %
5                     if the patient has hypertension              None
6                              platelets in the blood  kiloplatelets/mL
7              level of serum creatinine in the blood             mg/dL
8                  level of serum sodium in the blood             mEq/L
9                                        woman or man              None
10                       if the patient smokes or not              None
11                                   follow-up period              days
12    if the patient died during the follow-up period              None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no

In [5]:
df = pd.concat([X, y], axis=1)
display(df)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,death_event
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [7]:
Heart4.to_csv('heart_failure_clinical_records.csv', index=False)
print('Dataset saved to heart_failure_clinical_records.csv')

Dataset saved to heart_failure_clinical_records.csv

In [8]:
df.to_csv('original_heart_failure_data.csv', index=False)
print('Dataset saved to original_heart_failure_data.csv')

Dataset saved to original_heart_failure_data.csv

In [11]:
# cargar la base de datos
Heart4 = pd.read_csv("original_heart_failure_data.csv")

In [12]:
Heart4.shape

(299, 13)

In [13]:
Heart4.isnull().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
death_event                 0
dtype: int64

In [14]:
Heart4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    int64
 4   ejection_fraction         299 non-null    int64
 5   high_blood_pressure       299 non-null    int64
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    int64
 10  smoking                   299 non-null    int64
 11  time                      299 non-null    int64
 12  death_event               299 non-null    int64
dtypes: float64(3), int64(10)
memory usage: 30.5 KB

Veamos si hay duplicados

In [16]:
# Contar cuántas filas duplicadas hay
print("Número de duplicados:", Heart4.duplicated().sum())

Número de duplicados: 0

In [18]:
# Guardar Heart2 en un archivo CSV
Heart4.to_csv("Heart4.csv", index=False)

print("Archivo Heart4.csv descargado correctamente")

Archivo Heart4.csv descargado correctamente

### Descripción de las Variables

| Variable                 | Descripción                                                                          |
| :----------------------- | :----------------------------------------------------------------------------------- |
| **age**                  | Edad del paciente (años)                                                             |
| **anaemia**              | Disminución de glóbulos rojos o hemoglobina (booleano)                               |
| **creatinine_phosphokinase (CPK)** | Nivel de la enzima CPK en la sangre (mcg/L)                                           |
| **diabetes**             | Si el paciente tiene diabetes (booleano)                                             |
| **ejection_fraction**    | Porcentaje de sangre que sale del corazón en cada contracción (porcentaje)           |
| **high_blood_pressure**  | Si el paciente tiene hipertensión (booleano)                                         |
| **platelets**            | Plaquetas en la sangre (kiloplaquetas/mL)                                            |
| **sex**                  | Mujer o hombre (binario)                                                             |
| **serum_creatinine**     | Nivel de creatinina sérica en la sangre (mg/dL)                                      |
| **serum_sodium**         | Nivel de sodio sérico en la sangre (mEq/L)                                           |
| **smoking**              | Si el paciente fuma o no (booleano)                                                  |
| **time**                 | Periodo de seguimiento (días)                                                        |
| **death_event**          | Si el paciente falleció durante el periodo de seguimiento (booleano)                 |