In [7]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

In [1]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.6.17)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

Estamos trabajando con el conjunto de datos de diabetes.

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
cdc_diabetes_health_indicators = fetch_ucirepo(id=891)

# data (as pandas dataframes)
X = cdc_diabetes_health_indicators.data.features
y = cdc_diabetes_health_indicators.data.targets

# metadata
print(cdc_diabetes_health_indicators.metadata)

# variable information
print(cdc_diabetes_health_indicators.variables)

{'uci_id': 891, 'name': 'CDC Diabetes Health Indicators', 'repository_url': 'https://archive.ics.uci.edu/dataset/891/cdc+diabetes+health+indicators', 'data_url': 'https://archive.ics.uci.edu/static/public/891/data.csv', 'abstract': 'The Diabetes Health Indicators Dataset contains healthcare statistics and lifestyle survey information about people in general along with their diagnosis of diabetes. The 35 features consist of some demographics, lab test results, and answers to survey questions for each patient. The target variable for classification is whether a patient has diabetes, is pre-diabetic, or healthy. ', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Tabular', 'Multivariate'], 'num_instances': 253680, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Sex', 'Age', 'Education Level', 'Income'], 'target_col': ['Diabetes_binary'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2017, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C53919', 'creators': [], 'intro_paper': {'ID': 308, 'type': 'NATIVE', 'title': 'Incidence of End-Stage Renal Disease Attributed to Diabetes Among Persons with Diagnosed Diabetes — United States and Puerto Rico, 2000–2014', 'authors': 'Nilka Rios Burrows, MPH; Israel Hora, PhD; Linda S. Geiss, MA; Edward W. Gregg, PhD; Ann Albright, PhD', 'venue': 'Morbidity and Mortality Weekly Report', 'year': 2017, 'journal': None, 'DOI': None, 'URL': 'https://www.cdc.gov/mmwr/volumes/66/wr/mm6643a2.htm', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Dataset link: https://www.cdc.gov/brfss/annual_data/annual_2014.html', 'purpose': 'To better understand the relationship between  lifestyle and diabetes in the US', 'funded_by': 'The CDC', 'instances_represent': 'Each row represents a person participating in this study.', 'recommended_data_splits': 'Cross validation or a fixed train-test split could be used.', 'sensitive_data': '- Gender\n- Income\n- Education level', 'preprocessing_description': 'Bucketing of age', 'variable_info': '- Diabetes diagnosis\n- Demographics (race, sex)\n- Personal information (income, educations)\n- Health history (drinking, smoking, mental health, physical health)', 'citation': None}, 'external_url': 'https://www.kaggle.com/datasets/alexteboul/diabetes-health-indicators-dataset'}
                    name     role     type      demographic  \
0                     ID       ID  Integer             None
1        Diabetes_binary   Target   Binary             None
2                 HighBP  Feature   Binary             None
3               HighChol  Feature   Binary             None
4              CholCheck  Feature   Binary             None
5                    BMI  Feature  Integer             None
6                 Smoker  Feature   Binary             None
7                 Stroke  Feature   Binary             None
8   HeartDiseaseorAttack  Feature   Binary             None
9           PhysActivity  Feature   Binary             None
10                Fruits  Feature   Binary             None
11               Veggies  Feature   Binary             None
12     HvyAlcoholConsump  Feature   Binary             None
13         AnyHealthcare  Feature   Binary             None
14           NoDocbcCost  Feature   Binary             None
15               GenHlth  Feature  Integer             None
16              MentHlth  Feature  Integer             None
17              PhysHlth  Feature  Integer             None
18              DiffWalk  Feature   Binary             None
19                   Sex  Feature   Binary              Sex
20                   Age  Feature  Integer              Age
21             Education  Feature  Integer  Education Level
22                Income  Feature  Integer           Income

                                          description units missing_values
0                                          Patient ID  None             no
1         0 = no diabetes 1 = prediabetes or diabetes  None             no
2                          0 = no high BP 1 = high BP  None             no
3        0 = no high cholesterol 1 = high cholesterol  None             no
4   0 = no cholesterol check in 5 years 1 = yes ch...  None             no
5                                     Body Mass Index  None             no
6   Have you smoked at least 100 cigarettes in you...  None             no
7        (Ever told) you had a stroke. 0 = no 1 = yes  None             no
8   coronary heart disease (CHD) or myocardial inf...  None             no
9   physical activity in past 30 days - not includ...  None             no
10  Consume Fruit 1 or more times per day 0 = no 1...  None             no
11  Consume Vegetables 1 or more times per day 0 =...  None             no
12  Heavy drinkers (adult men having more than 14 ...  None             no
13  Have any kind of health care coverage, includi...  None             no
14  Was there a time in the past 12 months when yo...  None             no
15  Would you say that in general your health is: ...  None             no
16  Now thinking about your mental health, which i...  None             no
17  Now thinking about your physical health, which...  None             no
18  Do you have serious difficulty walking or clim...  None             no
19                                0 = female 1 = male  None             no
20  13-level age category (_AGEG5YR see codebook) ...  None             no
21  Education level (EDUCA see codebook) scale 1-6...  None             no
22  Income scale (INCOME2 see codebook) scale 1-8 ...  None             no

In [3]:
print('Primeros 5 registros de las características (X):')
display(X.head())

Primeros 5 registros de las características (X):

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4

In [4]:
print('\nPrimeros 5 registros de las etiquetas (y):')
display(y.head())

Primeros 5 registros de las etiquetas (y):

   Diabetes_binary
0                0
1                0
2                0
3                0
4                0

In [5]:
# Combine features (X) and targets (y) into a single DataFrame
data_combined = X.copy()
data_combined['Diabetes_binary'] = y

In [6]:
# Save the combined DataFrame to a CSV file
csv_filename = 'cdc_diabetes_data.csv'
data_combined.to_csv(csv_filename, index=False)

print(f"Dataset guardado exitosamente como '{csv_filename}'")

Dataset guardado exitosamente como 'cdc_diabetes_data.csv'

a partir de aqui empezamos fase de limpieza.

In [9]:

Diabetes = pd.read_csv("cdc_diabetes_data.csv")

print(Diabetes.iloc[:10, :10])  # primeras 10 filas y 10 columnas

Diabetes.head

Diabetes.shape

Diabetes.drop_duplicates()

print(Diabetes.drop_duplicates())

   HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  HeartDiseaseorAttack  \
0       1         1          1   40       1       0                     0
1       0         0          0   25       1       0                     0
2       1         1          1   28       0       0                     0
3       1         0          1   27       0       0                     0
4       1         1          1   24       0       0                     0
5       1         1          1   25       1       0                     0
6       1         0          1   30       1       0                     0
7       1         1          1   25       1       0                     0
8       1         1          1   30       1       0                     1
9       0         0          1   24       0       0                     0

   PhysActivity  Fruits  Veggies
0             0       0        1
1             1       0        0
2             0       1        0
3             1       1        1
4             1       1        1
5             1       1        1
6             0       0        0
7             1       0        1
8             0       1        1
9             0       0        1
        HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0            1         1          1   40       1       0
1            0         0          0   25       1       0
2            1         1          1   28       0       0
3            1         0          1   27       0       0
4            1         1          1   24       0       0
...        ...       ...        ...  ...     ...     ...
253675       1         1          1   45       0       0
253676       1         1          1   18       0       0
253677       0         0          1   28       0       0
253678       1         0          1   23       0       0
253679       1         1          1   25       0       0

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  NoDocbcCost  \
0                          0             0       0        1  ...            0
1                          0             1       0        0  ...            1
2                          0             0       1        0  ...            1
3                          0             1       1        1  ...            0
4                          0             1       1        1  ...            0
...                      ...           ...     ...      ...  ...          ...
253675                     0             0       1        1  ...            0
253676                     0             0       0        0  ...            0
253677                     0             1       1        0  ...            0
253678                     0             0       1        1  ...            0
253679                     1             1       1        0  ...            0

        GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  Income  \
0             5        18        15         1    0    9          4       3
1             3         0         0         0    0    7          6       1
2             5        30        30         1    0    9          4       8
3             2         0         0         0    0   11          3       6
4             2         3         0         0    0   11          5       4
...         ...       ...       ...       ...  ...  ...        ...     ...
253675        3         0         5         0    1    5          6       7
253676        4         0         0         1    0   11          2       4
253677        1         0         0         0    0    2          5       2
253678        3         0         0         0    1    7          5       1
253679        2         0         0         0    0    9          6       2

        Diabetes_binary
0                     0
1                     0
2                     0
3                     0
4                     0
...                 ...
253675                0
253676                1
253677                0
253678                0
253679                1

[229474 rows x 22 columns]

In [10]:
# sin duplicados Diabetes1

Diabetes1 = Diabetes.drop_duplicates()

print(Diabetes1.shape)

print("\nTotal de nulos en la base:")

print(Diabetes1.isnull().sum().sum())

print(Diabetes1.dtypes)

(229474, 22)

Total de nulos en la base:
0
HighBP                  int64
HighChol                int64
CholCheck               int64
BMI                     int64
Smoker                  int64
Stroke                  int64
HeartDiseaseorAttack    int64
PhysActivity            int64
Fruits                  int64
Veggies                 int64
HvyAlcoholConsump       int64
AnyHealthcare           int64
NoDocbcCost             int64
GenHlth                 int64
MentHlth                int64
PhysHlth                int64
DiffWalk                int64
Sex                     int64
Age                     int64
Education               int64
Income                  int64
Diabetes_binary         int64
dtype: object

In [11]:
# para ver una descripcion de los datos de la columna BMI

print(Diabetes1["BMI"].describe())

count    229474.000000
mean         28.687507
std           6.789204
min          12.000000
25%          24.000000
50%          27.000000
75%          32.000000
max          98.000000
Name: BMI, dtype: float64